### ISSUE TITLE
how to change height of content-header ?? 

### ISSUE THREAD

**Issue by deepaksaini143** [almasaeed2010/AdminLTE#1257]
how to change height of content-header ??

**Comment by REJack** [comment]
Add this to your custom css or modify it in AdminLTE.css Line 319, 
but i recommend a custom css to avoid additional work after further updates or fixes.
```css
.content-header > h1 {
    font-size: 28px;
}
```
