### ISSUE TITLE
pull-right-container interferes with alignment

### ISSUE THREAD

**Issue by hrj** [almasaeed2010/AdminLTE#1260]
See screenshot:

![adminlte-align](https://cloud.githubusercontent.com/assets/345879/20697280/e3a355bc-b61d-11e6-902f-4b43bdcdf70b.png)

The number 12 is not vertically aligned with the rest of the text.

The markup (from [gitbucket](https://github.com/gitbucket/gitbucket/)):
```html
<li class="active">
    <a href="/issues">
      <i class="menu-icon octicon octicon-issue-opened"></i> Issues  <span class="label label-primary pull-right-container">12</span> 
    </a>    
</li>
``` 

The relevant CSS:
```css
.sidebar-menu li>a>.pull-right-container {
    position: absolute;
    right: 10px;
    top: 50%;
    margin-top: -7px;
}
```

The CSS is assuming a particular font-size. However, I have minimum font size overriden in my browser. That is probably causing the mis-alignment.

If I simply remove the `top` and `margin-top` properties it works, and it seems like a good idea, although I am not sure if there are other side-effects.
