### ISSUE TITLE
Find the login page background image

### ISSUE THREAD

**Issue by jinji-hanbin** [almasaeed2010/AdminLTE#1281]
I would like to replace the login page background map, there is no recommended, or examples

**Comment by REJack** [comment]
Its styled over the class `login-page`.

Default is:
```css
.login-page, .register-page {
    background: #d2d6de none repeat scroll 0 0;
}
```
