### ISSUE TITLE
Table Fixed header

### ISSUE THREAD

**Issue by fareed38** [almasaeed2010/AdminLTE#1338]
I am trying to make a fixed header for table in adminlte, but did not get the desire result. Fixed header is appearing in below css but it is not horizontal scroll bar and not responsive.

```css
.fixedheader
{
position:fixed;
background-color: #ecf0f5;
margin-left:230px;
left:0;
right:0; 
padding: 15px 15px 0 15px;
}
```

My table is as follow
```php
echo "<table class='table table-hover table-striped' style='white-space: nowrap;'>";
echo "<thead class='content-headerFixed'>
<tr>
<th>data1</th>
<th>data2</th>
<th>data3</th>
<th>data1</th>
<th>data2</th>
<th>data3</th>
<th>data1</th>
<th>data2</th>
<th>data3</th>
<th>data1</th>
<th>data2</th>
<th>data3</th>
</tr>
</thead>
<tbody>
<tr>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
<th>11</th>
<th>12</th>
</tr>
</body></table>
```
