### ISSUE TITLE
Image width

### ISSUE THREAD

**Issue by reillo** [almasaeed2010/AdminLTE#158]
Image width causes other plugin to be broken. (i.e google map).

in core.less

``` css
/* All images should be responsive */
img {
    max-width: 100% !important;
}
```

Should this be a bug?
