### ISSUE TITLE
Remove the blue border box

### ISSUE THREAD

**Issue by konrph** [almasaeed2010/AdminLTE#1636]
![screenshot](https://user-images.githubusercontent.com/25053196/30153680-adb918c4-93b7-11e7-8d8d-a643d158a0da.png)

Hi
I've made a summary with an Icon behind.
When I click on the summary the border box has a blue highlighting which includes my popupbox.
Is there a way to remove this border? I can't find the line in the stylesheet
thanks in advance

**Comment by almasaeed2010** [comment]
This seems like either a shadow or outline. Try using:
```css
.element:focus,
.element:hover {
   outline: none !important;
   box-shadow: none !important;
}
```

Thanks!
