### ISSUE TITLE
Left Menu without header (logo)

### ISSUE THREAD

**Issue by simonreger** [almasaeed2010/AdminLTE#1652]
Hello,

is it possible to remove the Header in Left-Menu? See my snapshot.
How can i do this. Thanks.

![snap](https://user-images.githubusercontent.com/32191953/30735606-e9f85be6-9f7f-11e7-8290-1b8c3f0f1296.png)

**Comment by jreklund** [comment]
Add `hidden-xs` like so: `<a href="index2.html" class="logo hidden-xs">`

If you are using the "Fixed Layout" (like me) you will need to add this into your own stylesheet.
```css
@media (max-width: 767px) {
	.main-sidebar, .left-side, .fixed .content-wrapper, .fixed .right-side {
		padding-top: 50px;
	}
}
```

**Comment by simonreger** [comment]
Thanks. But how can i delete the space between the Menu and "Alexander Pierce". See my screenshot.
![screen](https://user-images.githubusercontent.com/32191953/30797999-332283dc-a1d8-11e7-9757-d9d3f7e6987e.PNG)

**Comment by jreklund** [comment]
```css
@media (max-width: 767px) {
	.main-sidebar, .left-side {
		padding-top: 50px;
	}
}
```
