### ISSUE TITLE
Bootstrap modal and oferflow

### ISSUE THREAD

**Issue by loveorigami** [almasaeed2010/AdminLTE#185]
If use 
```css
html,
body {
  overflow-x: hidden!important;
  font-family: 'Source Sans Pro', sans-serif;
  -webkit-font-smoothing: antialiased;
  min-height: 100%;
  background: #f9f9f9;
}
```
after bootstrap modal overflow-y not hidden
![modal1](https://cloud.githubusercontent.com/assets/98164/5550494/28851f4a-8bb8-11e4-8420-5c843b8a91e7.jpg)

If use overflow-x: hidden!important; only for body
```css
html,
body {
  font-family: 'Source Sans Pro', sans-serif;
  -webkit-font-smoothing: antialiased;
  min-height: 100%;
  background: #f9f9f9;
}
body {
  overflow-x: hidden!important;
}
```
bootstrap modal works correct
![modal2](https://cloud.githubusercontent.com/assets/98164/5550552/ffc52d1a-8bb8-11e4-9d8c-e82492f21d61.jpg)
