### ISSUE TITLE
Issue with chrome and dropdown

### ISSUE THREAD

**Issue by mihir7293** [almasaeed2010/AdminLTE#221]
First of all thank you for the great free admin panel.
I have noticed that after some time using AdminLTE( only happens in chrome browser)
drop downs on right top comes late after clicking.
I have inspected element in chrome open class is added as I click but drop down appears after some time

**Comment by almasaeed2010** [comment]
That's probably caused by the dropdowns animation. I am not sure how why only chrome is doing that on your machine. Test it on other computers and if the problem persists then the problem is with the machine you are using. Otherwise, it's a chrome rendering glitch. With AdminLTE 2 it might be better.

**Comment by kressly** [comment]
I have a friend who have the same problem with his HTC phone. And also The Ionicons do not show on HTC android phone so when someone has a new message for example, not only the Envelop is not showing but also the drop-down does not drop but it loads a page where you see the list of your messages.

**Comment by alejandrosack** [comment]
Hi,
i have same problem that mihir. When I use drop downs don't show anything. The render is very slowly.
The machine is not the problem, may be SO. I try Chorme in WinXp and same version of Chrome in Win7 and first fail.
Ideas????

**Comment by almasaeed2010** [comment]
The only solution I can think of is to remove the animation to optimize the rendering speed. To do so, remove lines 1044 to 1081 in AdminLTE.css

Here is what you need to remove
```css
/* Add fade animation to dropdown menus */
.open:not(.dropup) > .dropdown-menu {
  animation-name: fadeAnimation;
  animation-duration: .7s;
  animation-iteration-count: 1;
  animation-timing-function: ease;
  animation-fill-mode: forwards;
  -webkit-animation-name: fadeAnimation;
  -webkit-animation-duration: .7s;
  -webkit-animation-iteration-count: 1;
  -webkit-animation-timing-function: ease;
  -webkit-animation-fill-mode: forwards;
  -moz-animation-name: fadeAnimation;
  -moz-animation-duration: .7s;
  -moz-animation-iteration-count: 1;
  -moz-animation-timing-function: ease;
  -moz-animation-fill-mode: forwards;
}
@keyframes fadeAnimation {
  from {
    opacity: 0;
    top: 120%;
  }
  to {
    opacity: 1;
    top: 100%;
  }
}
@-webkit-keyframes fadeAnimation {
  from {
    opacity: 0;
    top: 120%;
  }
  to {
    opacity: 1;
    top: 100%;
  }
}
```
