### ISSUE TITLE
AdminLTE compiled together with Bootstrap.

### ISSUE THREAD

**Issue by ivantcholakov** [almasaeed2010/AdminLTE#274]
I tested compilation of Bootstrap 3 together with AdminLTE and other widgets that have LESS source published.
https://github.com/alxlit/bootstrap-chosen
https://github.com/jasny/bootstrap (the file selection form control)

I assume that AdminLTE should override some Bootstrap variables, so the other external widgets to be restyled accordingly.

I found a that the variable @gray should not been overridden, or the collision is to be resolved somehow - some colors get wrong.

Is it possible Bootstrap 3 and AdminLTE to be compiled together and the resulting single CSS to give identical visual appearance?

**Comment by ivantcholakov** [comment]
Within all the AdminLTE sources I renamed the variable @gray into @my-gray. Then I did the compilation using the following file, the visual result seems to be ok:

```less

// File: admin-theme.less


@import url(//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);


// Directories
@theme-path:                    "admin-theme/";
@default-assets-path:           "../../../assets/";
@default-assets-less-path:      "@{default-assets-path}less/";
@default-assets-less-lib-path:  "@{default-assets-less-path}lib/";


// Global mixins
@import "@{theme-path}mixins.less";

// Boostrap variables and mixins
@import "@{default-assets-less-lib-path}bootstrap-3/variables.less";
@import "@{default-assets-less-lib-path}bootstrap-3/mixins.less";


// AdminLTE variables
@import "@{default-assets-less-lib-path}AdminLTE/variables.less";


/*!
 *  Bootstrap 3
 */

// Reset and dependencies
@import "@{default-assets-less-lib-path}bootstrap-3/normalize.less";
@import "@{default-assets-less-lib-path}bootstrap-3/print.less";
@import "@{default-assets-less-lib-path}bootstrap-3/glyphicons.less";

// Core CSS
@import "@{default-assets-less-lib-path}bootstrap-3/scaffolding.less";
@import "@{default-assets-less-lib-path}bootstrap-3/type.less";
@import "@{default-assets-less-lib-path}bootstrap-3/code.less";
@import "@{default-assets-less-lib-path}bootstrap-3/grid.less";
@import "@{default-assets-less-lib-path}bootstrap-3/tables.less";
@import "@{default-assets-less-lib-path}bootstrap-3/forms.less";
@import "@{default-assets-less-lib-path}bootstrap-3/buttons.less";

// Components
@import "@{default-assets-less-lib-path}bootstrap-3/component-animations.less";
@import "@{default-assets-less-lib-path}bootstrap-3/dropdowns.less";
@import "@{default-assets-less-lib-path}bootstrap-3/button-groups.less";
@import "@{default-assets-less-lib-path}bootstrap-3/input-groups.less";
@import "@{default-assets-less-lib-path}bootstrap-3/navs.less";
@import "@{default-assets-less-lib-path}bootstrap-3/navbar.less";
@import "@{default-assets-less-lib-path}bootstrap-3/breadcrumbs.less";
@import "@{default-assets-less-lib-path}bootstrap-3/pagination.less";
@import "@{default-assets-less-lib-path}bootstrap-3/pager.less";
@import "@{default-assets-less-lib-path}bootstrap-3/labels.less";
@import "@{default-assets-less-lib-path}bootstrap-3/badges.less";
@import "@{default-assets-less-lib-path}bootstrap-3/jumbotron.less";
@import "@{default-assets-less-lib-path}bootstrap-3/thumbnails.less";
@import "@{default-assets-less-lib-path}bootstrap-3/alerts.less";
@import "@{default-assets-less-lib-path}bootstrap-3/progress-bars.less";
@import "@{default-assets-less-lib-path}bootstrap-3/media.less";
@import "@{default-assets-less-lib-path}bootstrap-3/list-group.less";
@import "@{default-assets-less-lib-path}bootstrap-3/panels.less";
@import "@{default-assets-less-lib-path}bootstrap-3/responsive-embed.less";
@import "@{default-assets-less-lib-path}bootstrap-3/wells.less";
@import "@{default-assets-less-lib-path}bootstrap-3/close.less";

// Components w/ JavaScript
@import "@{default-assets-less-lib-path}bootstrap-3/modals.less";
@import "@{default-assets-less-lib-path}bootstrap-3/tooltip.less";
@import "@{default-assets-less-lib-path}bootstrap-3/popovers.less";
@import "@{default-assets-less-lib-path}bootstrap-3/carousel.less";

// Utility classes
@import "@{default-assets-less-lib-path}bootstrap-3/utilities.less";
@import "@{default-assets-less-lib-path}bootstrap-3/responsive-utilities.less";


// Font Awesome
@import "@{default-assets-less-lib-path}font-awesome-4/font-awesome.less";


/*!
 *   AdminLTE
 *   Author: Almsaeed Studio
 *	 Website: Almsaeed Studio <http://almsaeedstudio.com>
 *   License: Open source - MIT
 *           Please visit http://opensource.org/licenses/MIT for more information
!*/

//MISC
//----
@import "@{default-assets-less-lib-path}AdminLTE/core.less";
@import "@{default-assets-less-lib-path}AdminLTE/mixins.less";

//COMPONENTS
//-----------
@import "@{default-assets-less-lib-path}AdminLTE/header.less";
@import "@{default-assets-less-lib-path}AdminLTE/sidebar.less";
@import "@{default-assets-less-lib-path}AdminLTE/dropdown.less";
@import "@{default-assets-less-lib-path}AdminLTE/forms.less";
@import "@{default-assets-less-lib-path}AdminLTE/progress-bars.less";
@import "@{default-assets-less-lib-path}AdminLTE/small-box.less";
@import "@{default-assets-less-lib-path}AdminLTE/boxes.less";
@import "@{default-assets-less-lib-path}AdminLTE/info-box.less";
@import "@{default-assets-less-lib-path}AdminLTE/timeline.less";
@import "@{default-assets-less-lib-path}AdminLTE/buttons.less";
@import "@{default-assets-less-lib-path}AdminLTE/callout.less";
@import "@{default-assets-less-lib-path}AdminLTE/alerts.less";
@import "@{default-assets-less-lib-path}AdminLTE/navs.less";
@import "@{default-assets-less-lib-path}AdminLTE/products.less";
@import "@{default-assets-less-lib-path}AdminLTE/table.less";
@import "@{default-assets-less-lib-path}AdminLTE/labels.less";
@import "@{default-assets-less-lib-path}AdminLTE/direct-chat.less";
@import "@{default-assets-less-lib-path}AdminLTE/users-list.less";
@import "@{default-assets-less-lib-path}AdminLTE/carousel.less";
@import "@{default-assets-less-lib-path}AdminLTE/modal.less";

//PAGES
//------
@import "@{default-assets-less-lib-path}AdminLTE/mailbox.less";
@import "@{default-assets-less-lib-path}AdminLTE/lockscreen.less";
@import "@{default-assets-less-lib-path}AdminLTE/login_and_register.less";
@import "@{default-assets-less-lib-path}AdminLTE/404_500_errors.less";
@import "@{default-assets-less-lib-path}AdminLTE/invoice.less";

//Skins
//-------
@import "@{default-assets-less-lib-path}AdminLTE/skins/skin-blue.less";
@import "@{default-assets-less-lib-path}AdminLTE/skins/skin-black.less";
@import "@{default-assets-less-lib-path}AdminLTE/skins/skin-red.less";
@import "@{default-assets-less-lib-path}AdminLTE/skins/skin-green.less";
@import "@{default-assets-less-lib-path}AdminLTE/skins/skin-yellow.less";
@import "@{default-assets-less-lib-path}AdminLTE/skins/skin-purple.less";

//Plugins
//--------
@import "@{default-assets-less-lib-path}AdminLTE/bootstrap-social.less";
@import "@{default-assets-less-lib-path}AdminLTE/fullcalendar.less";

//Miscellaneous
//-------------
@import "@{default-assets-less-lib-path}AdminLTE/miscellaneous.less";
```
