### ISSUE TITLE
.nav-pills focus, background still blue

### ISSUE THREAD

**Issue by Adysone** [almasaeed2010/AdminLTE#300]
Hello,

The v2 is very good, but (there is always a but) I found a graphic "bug" for nav-pills : after selecting a pill, it becomes blue. You have fixed this for hover, but not for the focus.

![image](https://cloud.githubusercontent.com/assets/6309463/6782036/f48d331c-d171-11e4-80c4-871d94af10e2.png)

I corrected that way:
I replaced
```css
.nav-pills > li.active > a,
.nav-pills > li.active > a:hover {
  background-color: #f4f4f4;
  border-top-color: #3c8dbc;
  color: #444;
}
```
By

```css
.nav-pills > li.active > a,
.nav-pills > li.active > a:hover,
.nav-pills > li.active > a:focus {
  background-color: #f4f4f4;
  border-top-color: #3c8dbc;
  color: #444;
}
```

Thank you for your work!

**Comment by almasaeed2010** [comment]
Hello,

Thank you for reporting this! I will get to it as soon as possible. A fix will be provided in v2.1.0.

**Comment by Adysone** [comment]
Hello, thank you for your reactivity :)

2015-03-23 15:38 GMT+01:00 Abdullah Almsaeed <notifications@github.com>:

> Hello,
>
> Thank you for reporting this! I will get to it as soon as possible. A fix
> will be provided in v2.1.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almasaeed2010/AdminLTE/issues/300#issuecomment-85028439>
> .
>



-- 
Anthony D.

**Comment by almasaeed2010** [comment]
Fixed in v2.1.0

**Comment by benphelps** [comment]
This still seems to be broken on `nav-stacked` `nav-pills`.  You can see the same as above here: https://almsaeedstudio.com/themes/AdminLTE/pages/mailbox/mailbox.html

This fixed it for me, pretty sure it's the wrong way to do it:

```css
.nav-pills > li.active > a:focus {
    background-color: inherit !important;
    color: inherit !important;
}
```
