### ISSUE TITLE
mixins.less .logo-variant bg-color customizing theme logo

### ISSUE THREAD

**Issue by gdogabriel** [almasaeed2010/AdminLTE#403]
If we replace the text of .logo with background-image then we have problems with mouse over. So I suggest to change `background` to `background-color` at file `build/less/mixins.less:40`:
```less
.logo-variant(@bg-color; @color: #fff; @border-bottom-color: transparent; @border-bottom-width: 0px) {
  background-color: @bg-color;
  ...
  &:hover {
    background: darken(@bg-color, 1%);
  }
}
```
To:
```less
.logo-variant(@bg-color; @color: #fff; @border-bottom-color: transparent; @border-bottom-width: 0px) {
  background-color: @bg-color;
  ...
  &:hover {
    background-color: darken(@bg-color, 1%);
  }
}
```
