### ISSUE TITLE
Internet Explorer: nav menu starts off screen and slides in on page load

### ISSUE THREAD

**Issue by kurtschindler** [almasaeed2010/AdminLTE#430]
Strange behavior in IE11 - the menu starts off screen to the left and transitions into place on page load. It makes the page-load experience really awkward.

Interestingly, this *does not* occur when IE's dev tools are open, so I wasn't able to verify in emulated IE10/9 versions.

**Comment by almasaeed2010** [comment]
We have discussed this issue before in #286. Unfortunately, we weren't able to find a solution. I apologize for the inconvenience and I'd appreciate any suggestions if you have any.

**Comment by kurtschindler** [comment]
Sure thing. I have no idea where to even start, but I'll follow up if I have any success.

A really awful workaround is to force IE9 render mode by adding the meta tag `<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9">`. In limited testing, I was quite surprised the rest of the site behaved normally, but I'm wary of making this a production-level "fix" as it's forcing IE back 2 versions.  I'm afraid that may cause unintended consequences elsewhere.

**Comment by enumag** [comment]
Took me about 15 minutes to find the cause and some solutions:
https://css-tricks.com/transitions-only-after-page-load/
http://stackoverflow.com/questions/14389566/stop-css3-transition-from-firing-on-page-load

**Comment by kurtschindler** [comment]
Fantastic, @enumag! The css-tricks solution didn't have any affect when implemented verbatim, but by selecting the relevant elements directly I was able to prevent all the weird transitions on load.  

I applied the following changes to my solution and things are working great. Consider this a poor-mans pull request - @almasaeed2010 you may wish to tweak the specifics just a bit:

Dropped this in the top of my first .less file:

```css
body.hold-transition {
	.content-wrapper, 
	.right-side, 
	.main-footer, 
	.main-sidebar, 
	.left-side, 
	.main-header > .navbar,
	.main-header .logo {
	  -webkit-transition: none !important;
	  -moz-transition: none !important;
	  -ms-transition: none !important;
	  -o-transition: none !important;
	  transition: none !important;
	}
}
```

And then simply remove the `.hold-transition` once page is loaded:

```javascript
$(function () {
    $('body').removeClass('hold-transition');
});
```
