### ISSUE TITLE
Add Slimscroll to simple table

### ISSUE THREAD

**Issue by dschueler** [almasaeed2010/AdminLTE#495]
Just a quick question I hope. 
Could anyone tell me how to add slim scroll to s simple table within a box. 

I would like to limit the table/box size and allow the user to scroll vertically to see the other rows. 

thanks...

p.s. Great theme here!!

**Comment by almasaeed2010** [comment]
Add a class to your table and apply simple css rules to it that enables overflow and sets a fixed height.

Example:

HTML
```html
<table class="table table-fixed-height">
  <tr>
    <th>Header</th>
  </tr>
  <tr>
    <td>Data</td>
  </tr>
</table>
```

CSS
```css
.table-fixed-height {
  overflow: auto;
  max-height: 300px;
}
```
