### ISSUE TITLE
page-break-inside: avoid not working in tables

### ISSUE THREAD

**Issue by gdespaux** [almasaeed2010/AdminLTE#585]
I have had this issue since Admine LTE v1 and it continues in the latest version. I have tried many, many different fixes. This is the closest it has gotten to breaking properly, however I absolutely need the breaks to happen between rows and not inside of them. I have tried setting the page-break-inside for tr, td, th, etc. but regardless of the setting the breaks appear in this manner. Anyone else have this issue or any solution for it? I'm now using the code as-is in the current version (v 2.2)

![pagebreak](https://cloud.githubusercontent.com/assets/7861929/8676621/3b6f39f0-2a10-11e5-89e3-081b48bd7c6a.png)

I love the AdminLTE template, I would appreciate any advice in solving this! Thank you!

**Comment by almasaeed2010** [comment]
According to [this answer](http://stackoverflow.com/questions/1763639/how-to-deal-with-page-breaks-when-printing-a-large-html-table), you could try adding the following code to your css.

```css
table  { page-break-inside:auto }
tr { page-break-inside:avoid; page-break-after:auto }
thead { display:table-header-group }
tfoot  { display:table-footer-group }
```
