### ISSUE TITLE
Problem with transfer label on new line in sidebar-menu

### ISSUE THREAD

**Issue by tim96** [almasaeed2010/AdminLTE#616]
@almasaeed2010 Hello.
After upgrade to version 2.2.0 we have a small problem with labels. You add:
```css
.sidebar-menu,
.main-sidebar .user-panel,
.sidebar-menu > li.header {
  white-space: nowrap!important;
  overflow: hidden;
}
```
And, if label for list in side menu is too long, it didn't transfer on new line.
You can see screenshots https://github.com/sonata-project/SonataAdminBundle/pull/3142

**Comment by tim96** [comment]
Screenshots
Before update:
![old_sonata](https://cloud.githubusercontent.com/assets/12379114/9033757/3b88ee06-39db-11e5-8628-6d21136f4323.png)
After update
![error_sonata](https://cloud.githubusercontent.com/assets/12379114/9033758/3b9a0bc8-39db-11e5-9237-0ff83586e06a.png)

**Comment by almasaeed2010** [comment]
Hello, 

If you need to use long text like that you probably should manually override the code. The problem with us doing it here is that it would cause problems in transitions for the sidebar-mini. Add the following code to your custom css file and include it after loading AdminLTE.

```css
.sidebar-menu,
.main-sidebar .user-panel,
.sidebar-menu > li.header {
  white-space: normal!important;
}
```

Thanks!
