### ISSUE TITLE
.input-size function

### ISSUE THREAD

**Issue by Soullivaneuh** [almasaeed2010/AdminLTE#713]
If I try this:

``` less
.input-xs {
  .input-size(22px; 1px; 5px; @font-size-small; @line-height-small; 3px);
}
```

I got a form with border radius that is not compliant with the theme.

This is "normal" because bootstrap function is like this:

``` less
.input-size(@input-height; @padding-vertical; @padding-horizontal; @font-size; @line-height; @border-radius) {
  height: @input-height;
  padding: @padding-vertical @padding-horizontal;
  font-size: @font-size;
  line-height: @line-height;
  border-radius: @border-radius;

  select& {
    height: @input-height;
    line-height: @input-height;
  }

  textarea&,
  select[multiple]& {
    height: auto;
  }
}
```

It would be better to provide an override of this function or at least, a custom one.
