### ISSUE TITLE
BUG in Internet Explorer ;(

### ISSUE THREAD

**Issue by gtacrazy** [almasaeed2010/AdminLTE#761]
The IE has a bug with scrollbar, look to gear in right side.

![bug-ie](https://cloud.githubusercontent.com/assets/15342444/10757719/ca583542-7c93-11e5-8cde-548f43da560d.jpg)

**Comment by crperlin** [comment]
fix this bug :
  you can  add css : 
```css
      body{
          -ms-overflow-style: scrollbar;
      }
```

work for my ie 11; great;

![qq 20151027203533](https://cloud.githubusercontent.com/assets/8272877/10758179/966e25c8-7cea-11e5-9be7-ac9bfd24f940.png)
