### ISSUE TITLE
Query:How to change the font-size of all text in Admin-lte

### ISSUE THREAD

**Issue by jkrishnak** [almasaeed2010/AdminLTE#769]
Hi , 
I have to change the font-size for entire text in Admin-lte , I have added the font-size tag in AdminLTE.css in body section , the font-size of text got changed but this has impacted the sidebar -collapse , a gap has been added  between the Menu after changing the font-size to 12px
body {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-family: 'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif;
  font-weight: 400;
  overflow-x: hidden;
  overflow-y: auto;
  font-size: 12px  
}

Request your help to change the font-size with out any impact.
Screen shot of the problem:
![image](https://cloud.githubusercontent.com/assets/15385953/10830245/9b163154-7ea4-11e5-98ec-011625130a07.png)

**Comment by almasaeed2010** [comment]
Hello,

I explored the bug for a bit and I think this is a construction issue on my part. I didn't create LESS variables to customize the fonts or the font size. Thus, it is really difficult to do that manually. Also, if you change the font now and then update to a newer version, you'll lose all your changes.

If changing the font size is that important and you must do it, then to fix your issue you should do the following:
- Find the new height of the menu item
- Go to AdminLTE.css and adjust the position of the treeview menu.
```css
.sidebar-mini.sidebar-collapse .sidebar-menu > li:hover > a > span:not(.pull-right),
  .sidebar-mini.sidebar-collapse .sidebar-menu > li:hover > .treeview-menu {
    display: block !important;
    position: absolute;
    width: 180px;
    left: 50px; /* Change 50px to the new height value. LINE 620*/
  }
```
