### ISSUE TITLE
@media print .content-wrapper transition disable

### ISSUE THREAD

**Issue by remain** [almasaeed2010/AdminLTE#775]
The problem with printing in Chrome-based browsers.
Need to disable css3 transition for @media print .content-wrapper container.

I fixed it this way:
```css
@media print {
    .content-wrapper,
    .right-side,
    .main-footer {
        transition: none !important;
    }
}
```

![screenshot-almsaeedstudio-chrome-print](https://cloud.githubusercontent.com/assets/11217397/10901458/735388fa-81f7-11e5-950b-7841e2564097.jpg)
