### ISSUE TITLE
Problem with .form-group-lg from bootsrap.css

### ISSUE THREAD

**Issue by githubjeka** [almasaeed2010/AdminLTE#801]
Border from bootsrap css overlap border from admin-lte

```css
.form-group-lg .form-control {
    height: 46px;
    padding: 10px 16px;
    font-size: 18px;
    line-height: 1.3333333;
    border-radius: 6px;
}
```

By default other inputs admin-lte have  **border-radius: 0;**

```css
.form-control {
    border-radius: 0;
    box-shadow: none;
    border-color: #d2d6de;
}
```

Code for reproducing
```html
<div class="form-group form-group-lg form-group-lg ">

     <label class="control-label col-sm-3" for="zoneparam-year">Year</label>

     <div class="col-sm-6">
          <input type="text" id="zoneparam-year" class="form-control">
     </div>

</div>
```
