### ISSUE TITLE
A white border is visible during focus/unfocus on the search input 

### ISSUE THREAD

**Issue by Grmiade** [almasaeed2010/AdminLTE#833]
![bug-adminlte](https://cloud.githubusercontent.com/assets/11244106/11613339/f4f597d2-9c1d-11e5-86f5-182dd7586ca1.gif)

A white border become visible during focus/unfocus on the search input.

```
.skin-blue .sidebar-form input[type="text"], .skin-blue .sidebar-form .btn {
    box-shadow: none;
    background-color: #374850;
    border: 1px solid transparent;
    height: 35px;
    -webkit-transition: all .3s ease-in-out;
    -o-transition: all .3s ease-in-out;
    transition: all .3s ease-in-out;
}
```

Clue: If we change `border: 1px solid transparent;` by `border: none;`, it's fixes.

**Comment by arcanedev-maroc** [comment]
Or you can do this:
```css
.skin-purple .sidebar-form input[type="text"] {
    //...
    border-right: none;
}

.skin-purple .sidebar-form .btn {
    //...
    border-left: none;
}
```
