### ISSUE TITLE
Where put page footer like `copyright 2014`?

### ISSUE THREAD

**Issue by yuomtheara** [almasaeed2010/AdminLTE#88]
I would like to put page footer like `copyright 2014`.
where put it?
Pl example for me.

**Comment by lenamtl** [comment]
Ok I see, I didn't saw this issus because my pages have a lot of content.
I will fix this and get back to you asap.

**Comment by lenamtl** [comment]
Ok I see I didn't got this issue because my pages have a lot of content (more long than the menu).
I will try to found a solution. I'm not sure if this will be possible the way the pages are built.

I think the aside should be done differently or maybe we need to add another wrapper....

**Comment by kressly** [comment]
Ok tks. But if u do find any solution, kindly share it will us so that we may all profit from it

**Comment by lenamtl** [comment]
Of course, I will need to find a solution for my project anyhow.

**Comment by almasaeed2010** [comment]
Since both the sidebar and the main content (right-side and left-side asides) are wrapped inside the wrapper. Placing the footer after the wrapper would solve your problem. That is, with a little bit of css tweaks to the footer, you will get the desired effect.

**Comment by almasaeed2010** [comment]
Here is an example of how to do that. This is the HTML to add after the .wrapper div:
```html
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <a class="btn btn-primary btn-sm" href="http://almsaeedstudio.com/docs">Docs</a>
  </div>
  <strong>Copyright &copy; 2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.					
</footer>
```

Here is the CSS. The code below uses less and was placed in the core.less file.
```css
.content {
	padding-bottom: 50px;
}
.main-footer {
	background: #fff;
	padding: 15px;
	color: #444;
	height: 50px;
	border-top: 1px solid #eee;
	margin-left: @left-side-width;
	margin-top: -50px;
	&.full-width {
		margin-left: 0;
	}
}
```

Finally, add this to app.js after line 31. This will allow the footer to stretch with the wrapper.
```js
$(".main-footer").toggleClass('full-width');
```

The full sidebar toggle function in app js which starts at line 18 should look like this:
```js
	//Enable sidebar toggle
	$("[data-toggle='offcanvas']").click(function (e) {
		e.preventDefault();

		//If window is small enough, enable sidebar push menu
		if ($(window).width() <= 992) {
			$('.row-offcanvas').toggleClass('active');
			$('.left-side').removeClass("collapse-left");
			$(".right-side").removeClass("strech");
			$('.row-offcanvas').toggleClass("relative");
		} else {
			//Else, enable content streching
			$('.left-side').toggleClass("collapse-left");
			$(".right-side").toggleClass("strech");
		}

		$(".main-footer").toggleClass('full-width');
	});
```

Screenshot of the final effect:
![screen shot 2015-01-03 at 3 00 33 pm](https://cloud.githubusercontent.com/assets/1512664/5603584/2a6921d6-935a-11e4-8287-4def64ddf386.png)

**Comment by kressly** [comment]
Wow,
I almost did it but i think i am missing something somewhere but i can not tell what and this is by copying and pasting the code as it is. Also for the core css is there not one } that is not right at the end ? The first } at the end closed the .main-footer { . Is the second } not an error. And even when i remove it, i still get this whether i remove it or not .

![footer](https://cloud.githubusercontent.com/assets/925132/5603844/48cddd7a-9390-11e4-9d7a-2082c0ee03d8.png)

**Comment by almasaeed2010** [comment]
The css code was using LESS. which means you need to compile it first. Here is the css precompiled (so just add it in your AdminLTE.css file.

```css
.content {
    padding-bottom: 50px;
}
.main-footer {
    background: #fff;
    padding: 15px;
    color: #444;
    height: 50px;
    border-top: 1px solid #eee;
    margin-left: 220px;
    margin-top: -50px;
}
.main-footer.full-width {
    margin-left: 0;
}
```

Let me know if this doesn't work. We might need to add some extra js code.
