### ISSUE TITLE
How to add title in navbar

### ISSUE THREAD

**Issue by vicebetancourt** [almasaeed2010/AdminLTE#900]
I want to add a title in the center of the navbar-static-top. 
Does anyone know how to do it?

**Comment by ikhsan017** [comment]
you can try to add new div after the ```.navbar-custom-menu``` with the following style

```css
.center-navbar{
  display: block; 
  text-align: center; 
  color: white; {{render_menu('admin_navbar')}}
  padding: 15px; 
  /* adjust based on your layout */
  margin-left: 50px; 
  margin-right: 300px;
}
```
so the result looks like

```html
<nav class="navbar navbar-static-top" role="navigation">
      {#-- Sidebar toggle button--#}
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu"><!-- notification etc here --></div>
        <div class="center-navbar"><!-- center navbar content here --></div>
    </nav>
```
so the
